# Error codes for Module 1
MISSING_COLUMN = "MISSING_COLUMN"
NEGATIVE_SPREAD = "NEGATIVE_SPREAD"
UNSORTED_INPUT = "UNSORTED_INPUT"
TIMEZONE_ERROR = "TIMEZONE_ERROR"
IO_ERROR = "IO_ERROR"
GAP_EXCESS = "GAP_EXCESS"
